#
# Service: proxy-scanner
# The following values may be set or changed to configure the proxy-scanner service
#
replicaCount: 1
image: lacework/lacework-proxy-scanner:0.2.15

name: lacework-proxy-scanner
serviceAccount:
  enabled: true

config:
  static_cache_location: /opt/lacework
  default_registry:
  lacework:
    account_name:
    integration_access_token:
  registries:
  - domain:
    name:
    ssl:
    type:
    auto_poll:
    is_public:
    auth_type:
    auth_header_name: Authorization
    credentials:
      user_name:
      password:
    notification_type:
    poll_frequency_minutes: 20
    disable_non_os_package_scanning: false
    go_binary_scanning:
      enable: false
      scan_directory_path: ""

  - domain:
    name:
    ssl:
    type:
    auto_poll:
    is_public:
    auth_type:
    auth_header_name: Authorization
    credentials:
      user_name:
      password:
    notification_type:
    poll_frequency_minutes: 20
    disable_non_os_package_scanning: false
    go_binary_scanning:
      enable: false
      scan_directory_path: ""

certs:
  skipCert: true
  serverCertificate:
  serverKey: